[package]
name = "ginto"
version = "0.1.0"
edition = "2024"

[dependencies]
ginto_diag = { path = "crates/diag" }
ginto_syntax = { path = "crates/syntax" }

[workspace]
members = ["crates/diag", "crates/syntax"]
resolver = "3"
